#-------------------------------
# General Site Settings

title: JiriKomarek.net | Landscape photography
description: Landscape photographer from the Czech Republic. Drahanská vrchovina, Haná, mountains and more. # this means to ignore newlines until "baseurl:"
#baseurl: "/blog" # the subpath of your site, e.g. /blog
#baseurl: "/galada" # the subpath of your site, e.g. /blog
url: "https://xkomczax.github.io/web/" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
author-name:   Jiri Komarek
author-avatar: jiri-komarek-avatar.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/jiri.komarek.3150 # Add your Facebook handle
#twitter:   https://twitter.com/JiriKomarek_net # Add your Facebook handle
instagram: https://www.instagram.com/komcza # Add your Facebook handle
linkedin:  https://www.linkedin.com/in/jiri-komarek-645729191/ # Add your LinkedIn handle
#500px:     https://500px.com/jirikomarek_net


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: true # To enable the instafeed, use the value true. To turn off use the value false. # XXX - to be enabled after I fully launch instagram account


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: jirikomarek.us4.list-manage.com/subscribe/post?u=1a0fdfcd670c9a3ab0315ef63&amp;id=6e3330f1ae # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
#paginate_path: "/page/:num"
paginate_path: "/page:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
